### ISSUE TITLE
gitignore dosyasının eklenmesi.

### ISSUE THREAD

**Issue by mevlanaayas** [tugberkcelik/Sample#1]

**Comment by tcelik** [comment]
Anlayamadım mevlana :)

**Comment by mevlanaayas** [comment]
https://help.github.com/articles/ignoring-files/

.gitignore dosyası oluşturup, buraya atmak istemeyeceğin dosyaları içine yazabilirsin. örnek: ".idea" klasörü, senin kullandığın ide oluşturuyor bunu git'te olmasına gerek olmayabilir. yine kodu derleyince çıkan dosyalar. out gibi.

buraya yüklemek istiyorsan ayrı tabi :)

**Comment by tcelik** [comment]
Aslında dediğin mantıklı başkası indirip, ide'de açmaya çalışsa ve derlerse out gine oluşacak. Ben git add --all komutu ile herşeyi yüklüyorum, uğraşmıyorum hangi dosyaları yükleyeyim diye. Sonra clone yapınca ayarları ile geliyor. .idea'da sanırım benim kendi yaptığım ayarları tutuyor. Tavsiyen için teşekkür ederim.

**Comment by mevlanaayas** [comment]
rica ederim :)

git add --all kkomutu ile eklediğinde buraya eklenmesini istemediklerin ".gitignore" dosyasında oluyor. 

https://github.com/mevlanaayas/mevlanaayas.github.io

şuraya bakabilirsin. git add -all dememe rağmen .idea buraya yüklenmiyor.
